import Image from 'next/image'
import type { ComponentPropsWithoutRef } from 'react'

type ImgIconProps = Omit<ComponentPropsWithoutRef<typeof Image>, 'src' | 'alt' | 'width' | 'height'> & {
  title?: string
}

// Hand-drawn illustrated icons (see public/icons/structures/) generated by
// the project owner and cropped from a single 3x2 reference sheet — one row
// of 3 castle designs, one row of 3 village designs. Named after their
// position on that sheet rather than an architectural label, since none of
// the three castle designs is literally a "ruin" — the variant identifier is
// purely an internal key for `pickVariant`'s deterministic random pick, it
// never surfaces to the player (the `title` prop, always "Hrad"/"Vesnice", is
// what's user-facing).
export const CASTLE_VARIANTS = ['castle-1', 'castle-2', 'castle-3'] as const
export type CastleVariant = (typeof CASTLE_VARIANTS)[number]

export const VILLAGE_VARIANTS = ['village-1', 'village-2', 'village-3'] as const
export type VillageVariant = (typeof VILLAGE_VARIANTS)[number]

function hashStringToIndex(value: string, modulo: number) {
  let hash = 0
  for (let i = 0; i < value.length; i++) {
    hash = (hash * 31 + value.charCodeAt(i)) | 0
  }
  return Math.abs(hash) % modulo
}

export function pickVariant<T>(seed: string, variants: readonly T[]): T {
  return variants[hashStringToIndex(seed, variants.length)]
}

function StructureImg({
  variant,
  title,
  style,
  className,
  ...props
}: ImgIconProps & { variant: string }) {
  return (
    <Image
      src={`/icons/structures/${variant}.png`}
      alt={title ?? ''}
      title={title}
      width={96}
      height={96}
      style={{ objectFit: 'contain', ...style }}
      className={className}
      {...props}
    />
  )
}

export function CastleIcon({ variant, ...props }: ImgIconProps & { variant: CastleVariant }) {
  return <StructureImg variant={variant} {...props} />
}

export function VillageIcon({ variant, ...props }: ImgIconProps & { variant: VillageVariant }) {
  return <StructureImg variant={variant} {...props} />
}

// Single fixed illustration (public/icons/structures/home.png, drawn by the
// project owner) — unlike castle/village there's only one home design, so no
// `pickVariant` seed selection is needed.
export function HomeIcon(props: ImgIconProps) {
  return <StructureImg variant="home" {...props} />
}

export function WallIcon(props: ImgIconProps) {
  return <StructureImg variant="wall" {...props} />
}