import type { ComponentPropsWithoutRef } from 'react'

type SvgIconProps = Omit<ComponentPropsWithoutRef<'svg'>, 'viewBox'> & {
  title?: string
}

type ImgIconProps = Omit<ComponentPropsWithoutRef<'img'>, 'src' | 'alt'> & {
  title?: string
}

// Hand-drawn illustrated icons (see public/icons/structures/) generated by
// the project owner and cropped from a single 3x2 reference sheet — one row
// of 3 castle designs, one row of 3 village designs. Named after their
// position on that sheet rather than an architectural label, since none of
// the three castle designs is literally a "ruin" — the variant identifier is
// purely an internal key for `pickVariant`'s deterministic random pick, it
// never surfaces to the player (the `title` prop, always "Hrad"/"Vesnice", is
// what's user-facing).
export const CASTLE_VARIANTS = ['castle-1', 'castle-2', 'castle-3'] as const
export type CastleVariant = (typeof CASTLE_VARIANTS)[number]

export const VILLAGE_VARIANTS = ['village-1', 'village-2', 'village-3'] as const
export type VillageVariant = (typeof VILLAGE_VARIANTS)[number]

function hashStringToIndex(value: string, modulo: number) {
  let hash = 0
  for (let i = 0; i < value.length; i++) {
    hash = (hash * 31 + value.charCodeAt(i)) | 0
  }
  return Math.abs(hash) % modulo
}

export function pickVariant<T>(seed: string, variants: readonly T[]): T {
  return variants[hashStringToIndex(seed, variants.length)]
}

function IconBase({ title, children, ...props }: SvgIconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      role="img"
      aria-label={title}
      aria-hidden={title ? undefined : true}
      {...props}
    >
      {title && <title>{title}</title>}
      {children}
    </svg>
  )
}

export function HomeIcon(props: SvgIconProps) {
  return (
    <IconBase {...props}>
      <path
        fill="currentColor"
        fillRule="evenodd"
        d="M4 11.5 11.7 5l2.5 2.1V5.7h2.1V9l3.7 3.2v1.6h-1.6V19H5.6v-5.9H4v-1.6Zm3.4 6h8.8v-5.7l-4.4-3.7-4.4 3.7v5.7Zm3-2.1h2.9v-3.5h-2.9v3.5Z"
        clipRule="evenodd"
      />
      <path fill="currentColor" d="M16.8 6.5h1.5V8h-1.5z" opacity="0.85" />
    </IconBase>
  )
}

function StructureImg({
  variant,
  title,
  style,
  className,
  ...props
}: ImgIconProps & { variant: string }) {
  return (
    <img
      src={`/icons/structures/${variant}.png`}
      alt={title}
      title={title}
      style={{ objectFit: 'contain', ...style }}
      className={className}
      {...props}
    />
  )
}

export function CastleIcon({ variant, ...props }: ImgIconProps & { variant: CastleVariant }) {
  return <StructureImg variant={variant} {...props} />
}

export function VillageIcon({ variant, ...props }: ImgIconProps & { variant: VillageVariant }) {
  return <StructureImg variant={variant} {...props} />
}