-- Chat schema + RLS
-- Global channel + direct messages.

create table chat_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references players(id),
  channel_type text not null check (channel_type in ('global', 'dm')),
  conversation_id uuid,
  recipient_id uuid references players(id),
  body text not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  deleted_by uuid references players(id),
  check (char_length(trim(body)) between 1 and 500),
  check (
    (channel_type = 'global' and conversation_id is null and recipient_id is null)
    or (channel_type = 'dm' and conversation_id is not null and recipient_id is not null)
  )
);

create table chat_blocks (
  blocker_id uuid not null references players(id),
  blocked_id uuid not null references players(id),
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table chat_read_state (
  player_id uuid not null references players(id),
  conversation_id uuid not null,
  last_read_at timestamptz not null,
  primary key (player_id, conversation_id)
);

create index chat_messages_global_idx
  on chat_messages (channel_type, created_at desc);

create index chat_messages_conversation_idx
  on chat_messages (conversation_id, created_at desc);

create index chat_messages_sender_idx
  on chat_messages (sender_id, created_at desc);

alter table chat_messages enable row level security;
alter table chat_blocks enable row level security;
alter table chat_read_state enable row level security;

create policy chat_messages_select_authenticated on chat_messages
  for select
  using (
    auth.uid() is not null
    and (
      (channel_type = 'global' and deleted_at is null)
      or (
        channel_type = 'dm'
        and (sender_id = auth.uid() or recipient_id = auth.uid())
        and (deleted_at is null or sender_id = auth.uid())
      )
    )
  );

create policy chat_blocks_select_own on chat_blocks
  for select
  using (blocker_id = auth.uid());

create policy chat_blocks_insert_own on chat_blocks
  for insert
  with check (blocker_id = auth.uid());

create policy chat_blocks_delete_own on chat_blocks
  for delete
  using (blocker_id = auth.uid());

create policy chat_read_state_select_own on chat_read_state
  for select
  using (player_id = auth.uid());

create policy chat_read_state_insert_own on chat_read_state
  for insert
  with check (player_id = auth.uid());

create policy chat_read_state_update_own on chat_read_state
  for update
  using (player_id = auth.uid())
  with check (player_id = auth.uid());

create policy chat_read_state_delete_own on chat_read_state
  for delete
  using (player_id = auth.uid());

grant select on chat_messages to authenticated;
grant select, insert, delete on chat_blocks to authenticated;
grant select, insert, update, delete on chat_read_state to authenticated;

revoke all on chat_messages, chat_blocks, chat_read_state from public, anon;
